import mongoose, { Schema, Document } from 'mongoose';

/**
 * Per-main-category naming scheme for attribute-name normalisation (Phase 2).
 * Generated by the LLM as a draft, edited and approved by an admin. Approving does not
 * touch products — per-product proposals are a later, separately reviewed step.
 */
export interface IAttributeNamingScheme extends Document {
    categoryId: mongoose.Types.ObjectId;
    status: 'draft' | 'approved';
    canonical: { id: string; name: string; description?: string; standard?: boolean }[];
    rules: {
        key: string;
        canonicalId: string | null;
        signatures?: string[];
        brands?: string[];
        confidence: 'high' | 'medium' | 'low';
        reason?: string;
        source: 'ai' | 'admin';
    }[];
    unresolved: { key: string; note: string }[];
    generation: {
        model?: string;
        startedAt?: Date;
        completedChunks: number;
        totalChunks: number;
    };
    approvedAt?: Date;
    approvedBy?: string;
    createdAt: Date;
    updatedAt: Date;
}

const AttributeNamingSchemeSchema: Schema = new Schema({
    categoryId: { type: Schema.Types.ObjectId, ref: 'Category', required: true, unique: true },
    status: { type: String, enum: ['draft', 'approved'], default: 'draft' },
    canonical: [{
        _id: false,
        id: { type: String, required: true },
        name: { type: String, required: true, trim: true },
        description: { type: String, trim: true },
        standard: { type: Boolean, default: false },
    }],
    rules: [{
        _id: false,
        key: { type: String, required: true },
        canonicalId: { type: String, default: null },
        signatures: { type: [String], default: undefined },
        brands: { type: [String], default: undefined },
        confidence: { type: String, enum: ['high', 'medium', 'low'], default: 'medium' },
        reason: { type: String },
        source: { type: String, enum: ['ai', 'admin'], default: 'ai' },
    }],
    unresolved: [{
        _id: false,
        key: { type: String, required: true },
        note: { type: String, default: '' },
    }],
    generation: {
        model: { type: String },
        startedAt: { type: Date },
        completedChunks: { type: Number, default: 0 },
        totalChunks: { type: Number, default: 0 },
    },
    approvedAt: { type: Date },
    approvedBy: { type: String },
}, {
    timestamps: true
});

if (process.env.NODE_ENV !== 'production' && mongoose.models.AttributeNamingScheme) {
    delete mongoose.models.AttributeNamingScheme;
}
export default (mongoose.models?.AttributeNamingScheme as mongoose.Model<IAttributeNamingScheme>) ??
    mongoose.model<IAttributeNamingScheme>('AttributeNamingScheme', AttributeNamingSchemeSchema);
